title = "Patux's Home"
baseURL = "http://patux.net"
languageCode = "en-us"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-1686459-1"
paginate  = 10

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"
enableRobotsTXT = true
disqusShortname = "patux-net"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    pre = "edit"
    url = "/posts/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    pre = "smile"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    pre = "rss"
    url = "/index.xml"
    weight = 5
  [[menu.nav]]
    name = "  "
    pre = "twitter"
    url = "https://twitter.com/patux"
    weight = 6
  [[menu.nav]]
    Name = "   "
    hideName = true
    pre = "linkedin"
    url = "https://www.linkedin.com/in/patux/"
    weight = 7

[params]
  favicon = "favicon.ico"
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Patux's random thoughts"
  footerText = "Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = false
